version: "3.8"
services:
  frontend:
    build: ./client
    image: hemanth0921/gog_frontend:latest   
    container_name: react-app
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
